[bell]
animation = "EaseOutExpo"
duration = 0

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#171a1b"
foreground = "#ebdbb2"

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
# family = "Source Nerd Font Mono"
# family = "Source Code Pro"

# family = "Source Code Pro Powerline"
family = "Hack Nerd Font Mono"
# family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Slash"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Slash"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Slash"
mods = "Control"
